permalink:           /work/:title
relative_permalinks: true

# Setup
title:               Dougal MacPherson
tagline:             'Illustrator'
description:         'Childrens book illustrator'
url:                 http://mrdougal.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Dougal MacPherson
  url:               https://twitter.com/15mindrawings
  email:             greetings@mrdougal.com


collections:
  work:
    output: true

defaults:
  - 
    scope:
      type: posts
    values:
      collection: work
      layout: work

# Custom vars
version:             1.0.0


# github overides the source directory, so unfortunately the site's content
# is mixed amoungst the site's config. Seperation of concerns need not apply here
destination: build
include: [_posts/images]
exclude: [run/*]
encoding: utf-8
safe: true
lsi: false